default:
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      parameter_overrides:
      - NotificationQueueArn=arn:aws:sqs:us-west-2:961341555982:multi-demo-dev-processor-notifications
      - S3StorageClass=STANDARD_IA
      - EnableVersioning=false
      - BackupRetentionDays=30
      resolve_s3: true
      tags:
      - Environment=dev
      - ManagedBy=samstacks
      - Project=MultiEnvironmentProcessor
      - ConfigMode=external
      stack_name: multi-demo-dev-storage
      s3_prefix: multi-demo-dev-storage
      region: us-west-2
      template: ../../stacks/storage/template.yaml
  global:
    parameters:
      beta_features: false
  build:
    parameters:
      template: ../../stacks/storage/template.yaml
version: 0.1
