default:
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      parameter_overrides:
      - Environment=dev
      - LogLevel=DEBUG
      - EnableXrayTracing=false
      - MaxRetries=3
      resolve_s3: true
      tags:
      - Environment=dev
      - ManagedBy=samstacks
      - Project=MultiEnvironmentProcessor
      - ConfigMode=external
      stack_name: multi-demo-dev-processor
      s3_prefix: multi-demo-dev-processor
      region: us-west-2
      template: ../../../stacks/processor/template.yaml
  global:
    parameters:
      beta_features: false
  build:
    parameters:
      template: ../../../stacks/processor/template.yaml
version: 0.1
