default:
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      parameter_overrides:
      - Environment=dev
      - EnableDetailedLogging=true
      - EnableXrayTracing=false
      region: us-west-2
      resolve_s3: true
      s3_prefix: samstacks-demo-dev-processor
      stack_name: samstacks-demo-dev-processor
      tags:
      - Environment=dev
      - ManagedBy=samstacks
      - Project=S3ObjectProcessor
  global:
    parameters:
      beta_features: false
version: 0.1
